[PHP]
memory_limit = 256M
max_execution_time = 300
upload_max_filesize = 50M
post_max_size = 50M
max_input_time = 120
date.timezone = UTC

[opcache]
opcache.enable = 0
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

[error]
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
log_errors = On
error_log = /var/www/storage/logs/php_errors.log

[xdebug]
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.idekey = VSCODE
xdebug.log = /var/www/storage/logs/xdebug.log
xdebug.discover_client_host = 1